'use server';

/**
 * @fileOverview Generates diagram images using Google Imagen 3.
 *
 * - generateDiagramImage - Function that generates an image from a text description
 * - Uses the existing Gemini API key manager for consistency
 */

import { GoogleGenAI } from "@google/genai";
import { geminiApiKeyManager } from '@root/gemini-api-key-manager';

export interface GenerateDiagramImageInput {
  description: string;
  aspectRatio?: '1:1' | '3:4' | '4:3' | '9:16' | '16:9';
}

export interface GenerateDiagramImageOutput {
  imageDataUri: string; // Base64 data URI
}

/**
 * Generate a diagram image using Google Imagen 3.
 * Uses the existing Gemini API key manager to ensure rate limiting and key rotation.
 */
export async function generateDiagramImage(
  input: GenerateDiagramImageInput
): Promise<GenerateDiagramImageOutput> {
  const startTime = Date.now();
  console.log('[Imagen] Starting diagram generation...');
  console.log(`[Imagen] Description: ${input.description.substring(0, 100)}...`);

  // Use the global API key manager
  const result = await geminiApiKeyManager.withKey(async (apiKey) => {
    const ai = new GoogleGenAI({ apiKey });

    try {
      const response = await ai.models.generateImages({
        model: 'imagen-3.0-generate-002',
        prompt: input.description,
        config: {
          numberOfImages: 1,
          aspectRatio: input.aspectRatio || '1:1',
          imageSize: '1K', // Use 1K for faster generation and lower cost
          personGeneration: 'dont_allow', // Educational diagrams shouldn't need people
        },
      });

      if (!response.generatedImages || response.generatedImages.length === 0) {
        throw new Error('No images generated by Imagen');
      }

      const imageBytes = response.generatedImages[0].image.imageBytes;
      if (!imageBytes) {
        throw new Error('No image bytes returned from Imagen');
      }

      // Convert base64 to data URI
      const imageDataUri = `data:image/png;base64,${imageBytes}`;

      const endTime = Date.now();
      const duration = ((endTime - startTime) / 1000).toFixed(2);
      console.log(`[Imagen] Diagram generated successfully in ${duration}s`);

      return { imageDataUri };
    } catch (error: any) {
      console.error('[Imagen] Error generating diagram:', error);
      throw new Error(`Failed to generate diagram: ${error.message}`);
    }
  });

  return result;
}
